# Generated by Django 4.1.4 on 2023-01-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pvcell", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="points",
            old_name="capacity",
            new_name="current",
        ),
        migrations.AddField(
            model_name="points",
            name="uid",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="points",
            name="voltage",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
